preload = ~/.config/hypr/wallpapers/stardust.jpg
preload = ~/.config/hypr/wallpapers/crater.jpg
preload = ~/.config/hypr/wallpapers/rain.jpg

wallpaper = DP-1, ~/.config/hypr/wallpapers/stardust.jpg
wallpaper = HDMI-A-1, ~/.config/hypr/wallpapers/crater.jpg
wallpaper = DP-2, ~/.config/hypr/wallpapers/rain.jpg
